# This is a basic workflow to help you get started with Actions

name: Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python package and dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[dev]
      # - name: Install tzdata on Windows
      #   if: startsWith(matrix.os, 'windows')
      #   run : python -m pip install tzdata
      - name: Test with pytest
        run: |
          pytest -v --html=test-results-${{ matrix.os }}-${{ matrix.python-version }}.html --self-contained-html
      - name: Upload pytest test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v1
        with:
          name: pytest-results-${{ matrix.os }}-${{ matrix.python-version }}
          path: test-results-${{ matrix.os }}-${{ matrix.python-version }}.html
